version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: api-entregas-rs
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: entregas
    ports:
      - "5432:5432"
